### ISSUE TITLE
Choose a code style and define Clang format rules

### ISSUE THREAD

**Issue by fntlnz** [elastic/ebpf#42]
Our clang format is currently empty and this leads to confusion.

We need to

- Pick a style for our C++ and C (Userspace and eBPF) code
- Write clang format rules, or use standard ones, to reflect that

Opening this because this was brought up many times by different team members so that we have a place to start a conversation.

**Comment by rhysre** [comment]
Chiming in to say that I don't really care what the code style is (within reason pls not GNU 😆 ), provided we enforce it and have a script we can quickly run to autoformat everything.

We all seem to be using 4 space indents. How about we just use the LLVM style and change the indent width to 4?

```
BasedOnStyle: llvm
IndentWidth: 4
```

CC'ing @mattnite @rcr @tabell @mjwolf in case they find this heretical and want to strongly disagree
