### ISSUE TITLE
EventProbe:  Compatibility with Kernels >= 5.10

### ISSUE THREAD

**Issue by fntlnz** [elastic/ebpf#66]
We agreed that as a starting point, for the EventProbe (network, file and process) , we want to support kernels >= 5.10.

We need to make sure our usage of helpers and function arguments is compatible with this requirement.

**Comment by fntlnz** [comment]
Regarding file events,https://github.com/elastic/ebpf/pull/65 contains  the changes to make them compatible with this requirement.

**Comment by mmat11** [comment]
Closing this as we now have specific issues: https://github.com/elastic/ebpf/issues/91, https://github.com/elastic/ebpf/issues/92. Existing helpers have been adjusted already.
