### ISSUE TITLE
Agree on the Kernel version used to generate vmlinux.h

### ISSUE THREAD

**Issue by mmat11** [elastic/ebpf#69]
From https://github.com/elastic/ebpf/pull/67#discussion_r795800871

> We can probably just generate it once but we would need to agree on a kernel to be used as base, document that and when we need to update we need to agree on the newer kernel.

The idea is to always use the prebuilt vmlinux (https://github.com/elastic/ebpf/tree/main/contrib/vmlinux#vmlinux) to build `elastic/ebpf` both in CI and locally

**Comment by fntlnz** [comment]
@leodido @rhysre @stanek-michal @nicholasberlin wdyt?

**Comment by rhysre** [comment]
Correct me if I'm wrong, but isn't the best choice here to just generate one on 5.16 (current latest) and just use that so we have as many definitions as possible? It should be backwards compatible.

**Comment by mmat11** [comment]
> isn't the best choice here to just generate one on 5.16 (current latest)

Yes, I think so

**Comment by stanek-michal** [comment]
> Correct me if I'm wrong, but isn't the best choice here to just generate one on 5.16 (current latest) and just use that so we have as many definitions as possible? It should be backwards compatible.

In case some definitions/offsets changed in newer versions, my understanding is that BTF will resolve such incompatibilities anyway? In that case it seems to be a good idea to just use the latest version for vmlinux.h. But if we care about pre-BTF kernels in any scenario, we need to be careful.

**Comment by rhysre** [comment]
> > Correct me if I'm wrong, but isn't the best choice here to just generate one on 5.16 (current latest) and just use that so we have as many definitions as possible? It should be backwards compatible.
> 
> In case some definitions/offsets changed in newer versions, my understanding is that BTF will resolve such incompatibilities anyway? In that case it seems to be a good idea to just use the latest version for vmlinux.h. But if we care about pre-BTF kernels in any scenario, we need to be careful.

Field offset changes are automatically handled by BTF relocations, if a field is actually _renamed_ or moved to a different struct, that detail will have to bleed into our code (e.g. via [bpf_core_field_exists](https://nakryiko.com/posts/bpf-core-reference-guide/#bpf-core-field-exists)) but the version of vmlinux.h we're using is totally independent of that and shouldn't affect things in any way.

**Comment by fntlnz** [comment]
Agree on keeping our vmlinux in sync with the latest stable (now 5.16.5)

**Comment by rhysre** [comment]
Closing this stale ticket as it's been resolved for a while.
