### ISSUE TITLE
Probes fail to verify pre-5.10.10

### ISSUE THREAD

**Issue by rhysre** [elastic/ebpf#91]
[This](https://github.com/elastic/ebpf/blob/main/GPL/EventProbe/PathResolver.h#L125) line fails the verifier on a pre-5.10.10 kernel. It seems that `buf` is spilled to the stack, and pre-5.10.10 `PTR_TO_MEM` values that were spilled to the stack lost their bounds information [see here](https://elixir.bootlin.com/linux/v5.10.10/source/kernel/bpf/verifier.c#L2191).

**Comment by htwing** [comment]
Reproduced the problem which probes fail to verify using 5.10 kernel by running EventsTrace in virtme.

R2 invalid mem access 'inv'.  <-----------------

==============================386: (07) r1 += -40
; curr_dentry   = (struct dentry *)BPF_CORE_READ(mnt, mnt_mountpoint);
387: (b7) r2 = 8
388: (85) call bpf_probe_read_kernel#113
389: (b7) r1 = 16
390: (0f) r7 += r1
; curr_dentry   = (struct dentry *)BPF_CORE_READ(mnt, mnt_mountpoint);
391: (79) r8 = *(u64 *)(r10 -40)
392: (bf) r1 = r10
; 
393: (07) r1 += -40
; mnt           = BPF_CORE_READ(mnt, mnt_parent);
394: (b7) r2 = 8
395: (bf) r3 = r7
396: (85) call bpf_probe_read_kernel#113
397: (b7) r7 = 0
; mnt           = BPF_CORE_READ(mnt, mnt_parent);
398: (79) r1 = *(u64 *)(r10 -40)
399: (7b) *(u64 *)(r10 -72) = r1
400: (b7) r2 = 32
401: (0f) r1 += r2
402: (7b) *(u64 *)(r10 -64) = r1
; 
403: (7b) *(u64 *)(r9 +0) = r7
 frame2: R0_w=invP(id=0) R1_w=invP(id=0) R2_w=invP32 R6=invP100 R7_w=invP0 R8_w=invP(id=0) R9=map_value(id=0,off=792,ks=4,vs=800,imm=0) R10=fp0 fp-8=mmmmmmmm fp-16=mmmmmmmm fp-24=mmmm???? fp-40=mmmmmmmm fp-64_w=mmmmmmmm fp-72_w=mmmmmmmm fp-80=map_value fp-88=mmmmmmmm fp-96=invP1 refs=4
; for (int i = 0; i < PATH_RESOLVER_MAX_COMPONENTS; i++) {
404: (07) r9 += 8
405: (07) r6 += 1
406: (bf) r7 = r8
; for (int i = 0; i < PATH_RESOLVER_MAX_COMPONENTS; i++) {
407: (15) if r6 == 0x65 goto pc+6
; if (truncated) {
414: (79) r1 = *(u64 *)(r10 -96)
415: (57) r1 &= 1
; 
416: (b7) r8 = 0
; if (truncated) {
417: (55) if r1 != 0x0 goto pc+1
419: (b7) r1 = 46
; buf[0] = '.';
420: (79) r2 = *(u64 *)(r10 -88)
421: (73) *(u8 *)(r2 +0) = r1
R2 invalid mem access 'inv'
processed 5806 insns (limit 1000000) max_states_per_insn 4 total_states 81 peak_states 81 mark_read 67
-- END PROG LOAD LOG --
libbpf: failed to load program 'kretprobe__vfs_unlink'
libbpf: failed to load object 'EventProbe_bpf'
libbpf: failed to load BPF skeleton 'EventProbe_bpf': -13
